matrix:
  include:
    - language: java
      jdk: oraclejdk8
      before_script:
        - cd backend/tests
        - mvn clean install  -DskipTests=true -Dmaven.javadoc.skip=true -B -V
     

    - language: node_js
      node_js: "8"
      before_script:
        - cd heimdall-frontend
        - npm install
        - npm build
      
      script:
        - cd ../
        - docker build -t heimdall-api  ./heimdall/heimdall-api
        #- docker build -t heimdall-api  ./heimdall/heimdall-api
