spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared

  profiles:
     active: native

server:
  port: 8888
  context-path: /

management:
    context-path: /manager
    security:
        enabled: false
    health: 
        mongo: 
            enabled: false
        redis: 
            enabled: false
        rabbit: 
            enabled: false    
        hystrix: 
            enabled: false    
        refresh: 
            enabled: false