heimdall-api-vVERSAO:
  image: conductorcr.azurecr.io/@conductorcr.namespace@/heimdall-api:@versao@
  labels:
    aplicacao: heimdall-api-prod
    io.rancher.scheduler.affinity:host_label: tipo=node
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=heimdall-api-vVERSAO/heimdall-api-vVERSAO
